<a href="https://colab.research.google.com/github/Raanggasa/221230043-Pengantar-ML/blob/main/week-02/latihan-praktikum-2-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LATIHAN**

In [1]:
import numpy as np

In [2]:
'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# ✅ TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    return (data - mean) / std

X_normalized = z_score_normalization(X)

# ✅ TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    data_clipped = np.clip(data, lower_bound, upper_bound)
    return data_clipped

X_cleaned = handle_outliers(X_normalized)

# ✅ TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    n_classes = np.max(labels) + 1
    one_hot = np.zeros((labels.shape[0], n_classes))
    one_hot[np.arange(labels.shape[0]), labels] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# ✅ TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    indices = np.arange(n_samples)
    np.random.shuffle(indices)

    test_size = int(n_samples * test_size)
    test_indices = indices[:test_size]
    train_indices = indices[test_size:]

    X_train, X_test = X[train_indices], X[test_indices]
    y_train, y_test = y[train_indices], y[test_indices]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# ✅ Assertion checks
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed")

✅ NumPy operations completed


In [3]:
print("Original data shape:", X.shape)
print("Normalized data mean:", np.mean(X_normalized, axis=0).round(3))
print("Normalized data std:", np.std(X_normalized, axis=0).round(3))
print("Sample cleaned data (first 5 rows):\n", X_cleaned[:5])
print("One-hot labels shape:", one_hot_labels.shape)
print("One-hot labels:\n", one_hot_labels)
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

Original data shape: (100, 5)
Normalized data mean: [-0.  0. -0. -0.  0.]
Normalized data std: [1. 1. 1. 1. 1.]
Sample cleaned data (first 5 rows):
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
One-hot labels shape: (7, 3)
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Train shape: (80, 5) Test shape: (20, 5)
