<a href="https://colab.research.google.com/github/Raanggasa/221230043-Pengantar-ML/blob/main/week-02/latihan-praktikum-4-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
#!pip install torch torchvision torchaudio

In [75]:
import torch
import numpy as np

In [76]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.8.0+cu126
CUDA available: False


# 1. TENSOR CREATION & TYPES

In [77]:
print("=== TENSOR CREATION ===")
# Various creation methods
tensor_zeros = torch.zeros(2, 3)                    # Zeros tensor
tensor_ones = torch.ones(2, 3)                      # Ones tensor
tensor_rand = torch.rand(2, 3)                      # Random [0,1)
tensor_randn = torch.randn(2, 3)                    # Normal distribution
tensor_arange = torch.arange(0, 10, 2)              # Like range()

print("Zeros tensor:\n", tensor_zeros)
print("Random tensor:\n", tensor_rand)
print("Arange tensor:", tensor_arange)

=== TENSOR CREATION ===
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor:
 tensor([[0.9142, 0.0409, 0.8343],
        [0.1474, 0.6872, 0.9231]])
Arange tensor: tensor([0, 2, 4, 6, 8])


# 2. DATA TYPES & SHAPE

In [78]:
print("\n=== DATA TYPES & SHAPE ===")
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

print("Integer tensor dtype:", tensor_int.dtype)
print("Float tensor dtype:", tensor_float.dtype)
print("Tensor shape:", tensor_float.shape)
print("Tensor size:", tensor_float.size())
print("Number of elements:", tensor_float.numel())


=== DATA TYPES & SHAPE ===
Integer tensor dtype: torch.int32
Float tensor dtype: torch.float32
Tensor shape: torch.Size([3])
Tensor size: torch.Size([3])
Number of elements: 3


# 3. ACCESS & SLICING

In [79]:
print("\n=== ACCESS & SLICING ===")
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original tensor:\n", tensor_2d)
print("Element [1,2]:", tensor_2d[1, 2])
print("First row:", tensor_2d[0, :])
print("Last column:", tensor_2d[:, -1])
print("Submatrix:\n", tensor_2d[0:2, 1:3])


=== ACCESS & SLICING ===
Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element [1,2]: tensor(6)
First row: tensor([1, 2, 3])
Last column: tensor([3, 6, 9])
Submatrix:
 tensor([[2, 3],
        [5, 6]])


# 4. RESHAPING

In [80]:
print("\n=== RESHAPING ===")
tensor_1d = torch.arange(12)
print("Original shape:", tensor_1d.shape)

reshaped = tensor_1d.reshape(3, 4)                  # Reshape
viewed = tensor_1d.view(3, 4)                       # View (shares memory)
transposed = reshaped.T                             # Transpose
flattened = reshaped.flatten()                      # Flatten

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: torch.Size([12])
Reshaped 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Transposed 4x3:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


# 5. MATHEMATICAL OPERATIONS

In [81]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("a + b =", a + b)                             # Element-wise
print("a * b =", a * b)
print("a ** 2 =", a ** 2)
print("torch.matmul:", torch.matmul(a, b))          # Dot product
print("torch.sum(a) =", torch.sum(a))               # Reduction


=== MATHEMATICAL OPERATIONS ===
a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])
torch.matmul: tensor(32.)
torch.sum(a) = tensor(6.)


# 6. AGGREGATION

In [82]:
print("\n=== AGGREGATION ===")
data = torch.randn(4, 5)                            # Random data
print("Data tensor:\n", data)
print("Global sum:", torch.sum(data))
print("Mean along dim 0:", torch.mean(data, dim=0)) # Column means
print("Max along dim 1:", torch.max(data, dim=1))   # Row maximums


=== AGGREGATION ===
Data tensor:
 tensor([[-0.3182,  1.2154,  1.4200, -0.0547,  0.6839],
        [-1.3246, -0.5161,  0.6002, -0.4702, -0.6086],
        [-0.0462, -1.6457, -0.4833, -0.7403,  0.3143],
        [ 0.1416,  1.0348, -0.6264, -0.5151,  0.6903]])
Global sum: tensor(-1.2491)
Mean along dim 0: tensor([-0.3869,  0.0221,  0.2276, -0.4451,  0.2700])
Max along dim 1: torch.return_types.max(
values=tensor([1.4200, 0.6002, 0.3143, 1.0348]),
indices=tensor([2, 2, 4, 1]))


# 7. BROADCASTING

In [83]:
print("\n=== BROADCASTING ===")
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix:\n", matrix)
print("Vector:", vector)
print("Broadcast result:\n", result)


=== BROADCASTING ===
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vector: tensor([10, 20, 30])
Broadcast result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


# 8. RANDOM OPERATIONS

In [84]:
print("\n=== RANDOM OPERATIONS ===")
torch.manual_seed(42)                               # Set seed
random_tensor = torch.rand(2, 3)                    # Uniform
normal_tensor = torch.randn(2, 3)                   # Normal
randint_tensor = torch.randint(0, 10, (2, 3))       # Integers

print("Uniform random:\n", random_tensor)
print("Normal random:\n", normal_tensor)
print("Random integers:\n", randint_tensor)


=== RANDOM OPERATIONS ===
Uniform random:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Normal random:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])
Random integers:
 tensor([[7, 6, 9],
        [6, 3, 1]])


In [85]:
# 9. CONCATENATION & SPLITTING

In [86]:
print("\n=== CONCATENATION & SPLITTING ===")
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

# Concatenation
cat_vertical = torch.cat([t1, t2], dim=0)           # Vertical
cat_horizontal = torch.cat([t1, t2], dim=1)         # Horizontal

print("Vertical concat:\n", cat_vertical)
print("Horizontal concat:\n", cat_horizontal)

# Splitting
chunks = torch.chunk(cat_vertical, 2, dim=0)        # Split into chunks
print("After splitting:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")


=== CONCATENATION & SPLITTING ===
Vertical concat:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Horizontal concat:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
After splitting:
Chunk 0:
tensor([[1, 2],
        [3, 4]])
Chunk 1:
tensor([[5, 6],
        [7, 8]])


In [87]:
# 10. GPU OPERATIONS

In [88]:
print("\n=== GPU OPERATIONS ===")
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor_gpu = tensor_2d.to(device)               # Move to GPU
    print(f"Tensor on: {tensor_gpu.device}")

    # Operations on GPU
    result_gpu = tensor_gpu + 1
    print("GPU operation result on CPU:", result_gpu.cpu())
else:
    print("GPU not available, using CPU")


=== GPU OPERATIONS ===
GPU not available, using CPU


In [89]:
# 🏋️ LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

### TENSOR OPERATIONS FOR NEURAL NETWORKS ###

In [90]:
import torch

'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# ✅ TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    # Operasi linear: y = XW + b
    return torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)
print("\n=== TODO 1: LINEAR LAYER (y = XW + b) ===")
print("Input shape:", X.shape)
print("Weights shape:", weights.shape)
print("Bias shape:", bias.shape)
print("Output (first 5 rows):\n", output[:5])
print("Output shape:", output.shape)

# ✅ TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    # ReLU: max(0, x)
    return torch.maximum(tensor, torch.tensor(0.0))

activated = relu_activation(output)
print("\n=== TODO 2: ReLU ACTIVATION ===")
print("Activated Output (first 5 rows):\n", activated[:5])
print("Jumlah nilai negatif yang diubah jadi 0:", torch.sum(output < 0).item())

# ✅ TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, epsilon=1e-5):
    # Normalisasi per feature: (x - mean) / (std + epsilon)
    mean = tensor.mean(dim=0, keepdim=True)
    std = tensor.std(dim=0, keepdim=True)
    return (tensor - mean) / (std + epsilon)

normalized = simple_batch_norm(X)
print("\n=== TODO 3: SIMPLE BATCH NORMALIZATION ===")
print("Mean per feature setelah normalisasi (≈ 0):\n", normalized.mean(dim=0))
print("Std per feature setelah normalisasi (≈ 1):\n", normalized.std(dim=0))
print("Normalized shape:", normalized.shape)

# ✅ TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    # Membuat tensor nol dengan ukuran [n_labels, num_classes]
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)
print("\n=== TODO 4: ONE-HOT ENCODING ===")
print("Labels asli:", labels.tolist())
print("One-hot encoded:\n", one_hot)
print("One-hot shape:", one_hot.shape)

# Validasi hasil
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
print("\n✅ PyTorch operations completed successfully")


### BONUS: ADVANCED TENSOR OPERATIONS ###

'''TODO: Matrix Multiplication dari Prinsip Dasar'''
def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    # Pastikan ukuran kolom A = baris B
    assert A.shape[1] == B.shape[0], "Ukuran matriks tidak cocok"
    result = torch.zeros(A.shape[0], B.shape[1])
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            result[i, j] = torch.sum(A[i, :] * B[:, j])
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("\n=== BONUS: MANUAL MATRIX MULTIPLICATION ===")
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Manual Result:\n", manual_result)
print("Torch Result:\n", torch_result)
print("Perbandingan hasil sama:", torch.allclose(manual_result, torch_result))

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"
print("✅ Advanced tensor operations completed successfully")


=== TODO 1: LINEAR LAYER (y = XW + b) ===
Input shape: torch.Size([32, 10])
Weights shape: torch.Size([10, 1])
Bias shape: torch.Size([1])
Output (first 5 rows):
 tensor([[ 4.7204],
        [ 0.1580],
        [-0.8167],
        [ 1.0195],
        [-0.7342]])
Output shape: torch.Size([32, 1])

=== TODO 2: ReLU ACTIVATION ===
Activated Output (first 5 rows):
 tensor([[4.7204],
        [0.1580],
        [0.0000],
        [1.0195],
        [0.0000]])
Jumlah nilai negatif yang diubah jadi 0: 18

=== TODO 3: SIMPLE BATCH NORMALIZATION ===
Mean per feature setelah normalisasi (≈ 0):
 tensor([-1.1176e-08,  1.8626e-08, -5.2154e-08,  7.4506e-09,  1.4901e-08,
        -3.7253e-09, -7.4506e-09, -1.3039e-08,  0.0000e+00,  1.4901e-08])
Std per feature setelah normalisasi (≈ 1):
 tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])
Normalized shape: torch.Size([32, 10])

=== TODO 4: ONE-HOT ENCODING ===
Labels asli: [2, 1, 2, 1, 1, 1, 1, 0, 1, 2]
One-hot en