<a href="https://colab.research.google.com/github/Raanggasa/221230043-Pengantar-ML/blob/main/week-02/praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum 2: Komputasi Numerik dengan NumPy Array

<a href="https://colab.research.google.com/github/pakizhan-ump/ml-umpontianak/blob/main/Modules/Week-02/Praktikum-02/Praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Tujuan Praktikum
Mahasiswa mampu menggunakan library **NumPy** untuk membuat dan memanipulasi array multidimensi serta memahami keunggulannya dibandingkan List untuk komputasi numerik.

## 📖 Dasar Teori
**NumPy (Numerical Python)** adalah library fundamental untuk komputasi ilmiah di Python. Struktur data utamanya adalah **ndarray (n-dimensional array)**, yang dirancang khusus untuk operasi numerik yang efisien. Keunggulan utamanya meliputi:
* **Homogeneous:** Semua elemen dalam sebuah array harus memiliki tipe data yang sama (misalnya, semua `float64` atau semua `int32`), yang memungkinkan penyimpanan memori yang lebih efisien.
* **Ukuran Tetap:** Ukuran array ditentukan saat pembuatan, membuatnya lebih dapat diprediksi dalam hal alokasi memori.
* **Efisiensi Memori & Kecepatan:** Operasi matematika pada NumPy array jauh lebih cepat karena dieksekusi oleh kode C yang terkompilasi, bukan melalui interpreter Python.
* **Mendukung Operasi Vektorisasi:** Memungkinkan operasi matematika dilakukan pada seluruh elemen array secara bersamaan tanpa perlu menulis *loop* `for`, membuat kode lebih ringkas dan cepat.

Dalam machine learning, data seperti gambar (matriks piksel), sinyal audio, atau fitur-fitur numerik hampir selalu direpresentasikan sebagai NumPy array.

In [1]:
import numpy as np

# 🔧 OPERASI FUNDAMENTAL NUMPY

# 1. ARRAY CREATION & TYPES

In [2]:
print("=== ARRAY CREATION ===")
arr1d = np.array([1, 2, 3, 4, 5])                    # 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])            # 2D array
arr3d = np.random.rand(2, 3, 4)                     # 3D random array

print("1D array shape:", arr1d.shape)
print("2D array shape:", arr2d.shape)
print("3D array shape:", arr3d.shape)

=== ARRAY CREATION ===
1D array shape: (5,)
2D array shape: (2, 3)
3D array shape: (2, 3, 4)


# 2. DATA TYPES

In [3]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_bool = np.array([True, False, True])

print("Data types:")
print("arr_int dtype:", arr_int.dtype)
print("arr_float dtype:", arr_float.dtype)

Data types:
arr_int dtype: int32
arr_float dtype: float64


# 3. ACCESS & SLICING

In [4]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("\n=== ACCESS & SLICING ===")
print("Element [1,2]:", matrix[1, 2])                # Single element
print("Row 1:", matrix[1, :])                        # Entire row
print("Column 2:", matrix[:, 2])                     # Entire column
print("Submatrix 2x2:\n", matrix[0:2, 1:3])          # Submatrix
print("Every other row:\n", matrix[::2, :])          # Step slicing


=== ACCESS & SLICING ===
Element [1,2]: 7
Row 1: [5 6 7 8]
Column 2: [ 3  7 11]
Submatrix 2x2:
 [[2 3]
 [6 7]]
Every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


# 4. RESHAPING

In [5]:
print("\n=== RESHAPING ===")
arr = np.arange(12)                                  # 0-11
print("Original shape:", arr.shape)
reshaped = arr.reshape(3, 4)                        # Reshape to 3x4
flattened = reshaped.flatten()                      # Back to 1D
transposed = reshaped.T                             # Transpose

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: (12,)
Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed 4x3:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


# 5. MATHEMATICAL OPERATIONS

In [6]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)                             # Element-wise add
print("a * b =", a * b)                             # Element-wise multiply
print("a ** 2 =", a ** 2)                           # Power
print("np.dot(a, b) =", np.dot(a, b))               # Dot product


=== MATHEMATICAL OPERATIONS ===
a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]
np.dot(a, b) = 32


# 6. AGGREGATION

In [7]:
print("\n=== AGGREGATION ===")
data = np.random.rand(5, 4)                         # 5x4 random data
print("Data:\n", data)
print("Sum all:", np.sum(data))
print("Mean all:", np.mean(data))
print("Std all:", np.std(data))
print("Sum columns:", np.sum(data, axis=0))         # Along columns
print("Mean rows:", np.mean(data, axis=1))          # Along rows


=== AGGREGATION ===
Data:
 [[0.71463439 0.46256957 0.72407636 0.30243468]
 [0.05368344 0.98783045 0.88480211 0.72515288]
 [0.18131337 0.76399502 0.69187515 0.94407924]
 [0.42898672 0.14046413 0.05678507 0.34438426]
 [0.29359284 0.17734717 0.34347297 0.06832429]]
Sum all: 9.289804111729609
Mean all: 0.46449020558648046
Std all: 0.3053875305290944
Sum columns: [1.67221076 2.53220635 2.70101166 2.38437535]
Mean rows: [0.55092875 0.66286722 0.6453157  0.24265504 0.22068432]


# 7. BROADCASTING

In [8]:
print("\n=== BROADCASTING ===")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix + Vector:\n", result)


=== BROADCASTING ===
Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


# 8. RANDOM OPERATIONS

In [9]:
print("\n=== RANDOM OPERATIONS ===")
random_arr = np.random.rand(3, 3)                   # Uniform [0,1)
normal_arr = np.random.randn(3, 3)                  # Normal distribution
integers = np.random.randint(0, 100, (3, 3))        # Random integers

print("Uniform random:\n", random_arr)
print("Normal random:\n", normal_arr)
print("Random integers:\n", integers)


=== RANDOM OPERATIONS ===
Uniform random:
 [[0.32009274 0.9120388  0.61644141]
 [0.04252021 0.04842646 0.99245444]
 [0.2039025  0.39752042 0.47859344]]
Normal random:
 [[ 1.36431704 -1.17905987 -1.69427395]
 [ 1.48771242 -2.59728043 -1.14801283]
 [ 0.81318754  0.87891248 -0.66393304]]
Random integers:
 [[41 27 66]
 [55 67 94]
 [15 44 11]]


# 9. SPLITTING & JOINING

In [10]:
print("\n=== SPLITTING & JOINING ===")
arr = np.arange(12).reshape(3, 4)
sub_arrays = np.split(arr, 3, axis=0)               # Split along rows
print("Original:\n", arr)
print("After split:")
for i, sub in enumerate(sub_arrays):
    print(f"Part {i}:\n{sub}")

# Joining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
joined = np.concatenate([arr1, arr2], axis=0)       # Vertical join
print("After concatenation:\n", joined)


=== SPLITTING & JOINING ===
Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After split:
Part 0:
[[0 1 2 3]]
Part 1:
[[4 5 6 7]]
Part 2:
[[ 8  9 10 11]]
After concatenation:
 [[1 2]
 [3 4]
 [5 6]]


# 10. CONDITIONAL OPERATIONS

In [11]:
print("\n=== CONDITIONAL OPERATIONS ===")
data = np.array([10, 25, 30, 45, 50, 65])
mask = data > 30                                    # Boolean mask
filtered = data[mask]                               # Filter with mask
print("Data > 30:", filtered)

# Where operation
result = np.where(data > 30, data, 0)               # Replace conditionally
print("Where > 30 else 0:", result)


=== CONDITIONAL OPERATIONS ===
Data > 30: [45 50 65]
Where > 30 else 0: [ 0  0  0 45 50 65]


# 🏋️ LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

### DATA PREPROCESSING DENGAN NUMPY ###

In [12]:
import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# ✅ TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    return (data - mean) / std

X_normalized = z_score_normalization(X)

# ✅ TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    data_clipped = np.clip(data, lower_bound, upper_bound)
    return data_clipped

X_cleaned = handle_outliers(X_normalized)

# ✅ TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    n_classes = np.max(labels) + 1
    one_hot = np.zeros((labels.shape[0], n_classes))
    one_hot[np.arange(labels.shape[0]), labels] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# ✅ TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    indices = np.arange(n_samples)
    np.random.shuffle(indices)

    test_size = int(n_samples * test_size)
    test_indices = indices[:test_size]
    train_indices = indices[test_size:]

    X_train, X_test = X[train_indices], X[test_indices]
    y_train, y_test = y[train_indices], y[test_indices]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# ✅ Assertion checks
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed")

✅ NumPy operations completed
