<a href="https://colab.research.google.com/github/Raanggasa/221230043-Pengantar-ML/blob/main/week-02/praktikum_4_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum 4: Pengenalan Tensor pada PyTorch

<a href="https://colab.research.google.com/github/pakizhan-ump/ml-umpontianak/blob/main/Modules/Week-02/Praktikum-02/praktikum_4_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Tujuan Praktikum
Mahasiswa memahami struktur data dasar dalam library **PyTorch**, yaitu **Tensor**, dan mampu melakukan operasi-operasi fundamental yang menjadi dasar dari komputasi deep learning.

## 📖 Dasar Teori
**PyTorch** adalah salah satu *framework* deep learning terpopuler. Unit data fundamental di PyTorch adalah **Tensor**. Secara konseptual, sebuah tensor adalah generalisasi dari vektor dan matriks ke dimensi yang lebih tinggi.
* Skalar = Tensor 0D
* Vektor = Tensor 1D
* Matriks = Tensor 2D

Tensor sangat mirip dengan NumPy ndarray, namun memiliki dua keunggulan krusial untuk deep learning:
1.  **Akselerasi GPU:** Tensor dapat dengan mudah dipindahkan ke *Graphics Processing Unit* (GPU) untuk mendapatkan percepatan komputasi yang masif. Ini sangat penting untuk melatih model deep learning yang kompleks pada data besar.
2.  **Dukungan Autograd:** PyTorch dapat secara otomatis melacak histori operasi pada tensor dan menghitung gradien (turunan) dari operasi tersebut. Fitur ini, yang disebut *automatic differentiation*, adalah inti dari algoritma *backpropagation* yang digunakan untuk melatih hampir semua jaringan saraf tiruan.


# 🔧 OPERASI FUNDAMENTAL PYTORCH

In [ ]:
#!pip install torch torchvision torchaudio

In [ ]:
import torch
import numpy as np

In [ ]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.8.0+cu126
CUDA available: False


# 1. TENSOR CREATION & TYPES

In [ ]:
print("=== TENSOR CREATION ===")
# Various creation methods
tensor_zeros = torch.zeros(2, 3)                    # Zeros tensor
tensor_ones = torch.ones(2, 3)                      # Ones tensor
tensor_rand = torch.rand(2, 3)                      # Random [0,1)
tensor_randn = torch.randn(2, 3)                    # Normal distribution
tensor_arange = torch.arange(0, 10, 2)              # Like range()

print("Zeros tensor:\n", tensor_zeros)
print("Random tensor:\n", tensor_rand)
print("Arange tensor:", tensor_arange)

=== TENSOR CREATION ===
Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor:
 tensor([[0.1830, 0.4459, 0.5643],
        [0.9260, 0.2614, 0.8203]])
Arange tensor: tensor([0, 2, 4, 6, 8])


# 2. DATA TYPES & SHAPE

In [ ]:
print("\n=== DATA TYPES & SHAPE ===")
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

print("Integer tensor dtype:", tensor_int.dtype)
print("Float tensor dtype:", tensor_float.dtype)
print("Tensor shape:", tensor_float.shape)
print("Tensor size:", tensor_float.size())
print("Number of elements:", tensor_float.numel())


=== DATA TYPES & SHAPE ===
Integer tensor dtype: torch.int32
Float tensor dtype: torch.float32
Tensor shape: torch.Size([3])
Tensor size: torch.Size([3])
Number of elements: 3


# 3. ACCESS & SLICING

In [ ]:
print("\n=== ACCESS & SLICING ===")
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original tensor:\n", tensor_2d)
print("Element [1,2]:", tensor_2d[1, 2])
print("First row:", tensor_2d[0, :])
print("Last column:", tensor_2d[:, -1])
print("Submatrix:\n", tensor_2d[0:2, 1:3])


=== ACCESS & SLICING ===
Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Element [1,2]: tensor(6)
First row: tensor([1, 2, 3])
Last column: tensor([3, 6, 9])
Submatrix:
 tensor([[2, 3],
        [5, 6]])


# 4. RESHAPING

In [ ]:
print("\n=== RESHAPING ===")
tensor_1d = torch.arange(12)
print("Original shape:", tensor_1d.shape)

reshaped = tensor_1d.reshape(3, 4)                  # Reshape
viewed = tensor_1d.view(3, 4)                       # View (shares memory)
transposed = reshaped.T                             # Transpose
flattened = reshaped.flatten()                      # Flatten

print("Reshaped 3x4:\n", reshaped)
print("Transposed 4x3:\n", transposed)
print("Flattened:", flattened)


=== RESHAPING ===
Original shape: torch.Size([12])
Reshaped 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Transposed 4x3:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


# 5. MATHEMATICAL OPERATIONS

In [ ]:
print("\n=== MATHEMATICAL OPERATIONS ===")
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("a + b =", a + b)                             # Element-wise
print("a * b =", a * b)
print("a ** 2 =", a ** 2)
print("torch.matmul:", torch.matmul(a, b))          # Dot product
print("torch.sum(a) =", torch.sum(a))               # Reduction


=== MATHEMATICAL OPERATIONS ===
a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])
torch.matmul: tensor(32.)
torch.sum(a) = tensor(6.)


# 6. AGGREGATION

In [ ]:
print("\n=== AGGREGATION ===")
data = torch.randn(4, 5)                            # Random data
print("Data tensor:\n", data)
print("Global sum:", torch.sum(data))
print("Mean along dim 0:", torch.mean(data, dim=0)) # Column means
print("Max along dim 1:", torch.max(data, dim=1))   # Row maximums


=== AGGREGATION ===
Data tensor:
 tensor([[-8.5424e-01,  5.3882e-01, -5.2649e-01, -1.3320e+00,  1.7389e+00],
        [-9.4229e-01,  1.1617e+00,  2.0278e+00, -1.8071e+00, -5.5707e-01],
        [-2.2706e-01,  6.5751e-01,  1.2293e+00, -1.2231e-03, -1.1441e+00],
        [-1.0940e+00, -5.4540e-01, -4.8224e-01,  1.0615e+00, -6.3780e-01]])
Global sum: tensor(-1.7356)
Mean along dim 0: tensor([-0.7794,  0.4532,  0.5621, -0.5197, -0.1500])
Max along dim 1: torch.return_types.max(
values=tensor([1.7389, 2.0278, 1.2293, 1.0615]),
indices=tensor([4, 2, 2, 3]))


# 7. BROADCASTING

In [ ]:
print("\n=== BROADCASTING ===")
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([10, 20, 30])

result = matrix + vector                            # Broadcasting
print("Matrix:\n", matrix)
print("Vector:", vector)
print("Broadcast result:\n", result)


=== BROADCASTING ===
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vector: tensor([10, 20, 30])
Broadcast result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


# 8. RANDOM OPERATIONS

In [ ]:
print("\n=== RANDOM OPERATIONS ===")
torch.manual_seed(42)                               # Set seed
random_tensor = torch.rand(2, 3)                    # Uniform
normal_tensor = torch.randn(2, 3)                   # Normal
randint_tensor = torch.randint(0, 10, (2, 3))       # Integers

print("Uniform random:\n", random_tensor)
print("Normal random:\n", normal_tensor)
print("Random integers:\n", randint_tensor)


=== RANDOM OPERATIONS ===
Uniform random:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Normal random:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])
Random integers:
 tensor([[7, 6, 9],
        [6, 3, 1]])


In [ ]:
# 9. CONCATENATION & SPLITTING

In [ ]:
print("\n=== CONCATENATION & SPLITTING ===")
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

# Concatenation
cat_vertical = torch.cat([t1, t2], dim=0)           # Vertical
cat_horizontal = torch.cat([t1, t2], dim=1)         # Horizontal

print("Vertical concat:\n", cat_vertical)
print("Horizontal concat:\n", cat_horizontal)

# Splitting
chunks = torch.chunk(cat_vertical, 2, dim=0)        # Split into chunks
print("After splitting:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")


=== CONCATENATION & SPLITTING ===
Vertical concat:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Horizontal concat:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
After splitting:
Chunk 0:
tensor([[1, 2],
        [3, 4]])
Chunk 1:
tensor([[5, 6],
        [7, 8]])


In [ ]:
# 10. GPU OPERATIONS

In [ ]:
print("\n=== GPU OPERATIONS ===")
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor_gpu = tensor_2d.to(device)               # Move to GPU
    print(f"Tensor on: {tensor_gpu.device}")

    # Operations on GPU
    result_gpu = tensor_gpu + 1
    print("GPU operation result on CPU:", result_gpu.cpu())
else:
    print("GPU not available, using CPU")


=== GPU OPERATIONS ===
GPU not available, using CPU


In [ ]:
# 🏋️ LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

### TENSOR OPERATIONS FOR NEURAL NETWORKS ###

In [ ]:
'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return X @ W + b  # atau torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.maximum(tensor, torch.tensor(0.0))

activated = relu_activation(output)

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, epsilon=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)  # per feature across batch
    std = tensor.std(dim=0, keepdim=True)
    return (tensor - mean) / (std + epsilon)

normalized = simple_batch_norm(X)

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes, dtype=torch.float32)
    one_hot[torch.arange(labels.size(0)), labels] = 1.0
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
print("✅ PyTorch operations completed")

### BONUS: ADVANCED TENSOR OPERATIONS ###

'''TODO: Matrix Multiplication dari Prinsip Dasar'''
def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    m, n = A.shape
    n2, p = B.shape
    assert n == n2, "Ukuran tidak cocok untuk perkalian matriks"

    result = torch.zeros((m, p), dtype=A.dtype)
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"
print("✅ Advanced tensor operations completed")

✅ PyTorch operations completed
✅ Advanced tensor operations completed
